package Running;
public enum Token {
    INTEGER, BOOLEAN_STRING, LITERAL_STRING, IDENTIFIER, KEYWORLD, TYPE, KEYWORD, 
    ARITHMETIC_OPERATOR, ASSIGNMENT_OPERATOR, COMPARISON_OPERATOR, SEMI, LBRACE, RBRACE, LPAREN, RPAREN, 
    LBRACK, RBRACK, COMMA, WHITESPACE, INVALID
}